# Generated by Django 3.2.7 on 2021-11-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
