# Generated by Django 3.2.7 on 2021-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_goods_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='about',
            field=models.TextField(),
        ),
    ]
