# Generated by Django 3.2.7 on 2021-12-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='size',
            field=models.CharField(default='Free', max_length=10),
        ),
    ]
