# Generated by Django 3.2.7 on 2021-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_good_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='size',
        ),
    ]
