# Generated by Django 3.2.7 on 2021-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211203_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
        migrations.AddField(
            model_name='good',
            name='sizes',
            field=models.ManyToManyField(to='home.Size'),
        ),
    ]
