# Generated by Django 3.2.7 on 2021-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211203_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sizes',
        ),
        migrations.AddField(
            model_name='good',
            name='inventory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
