# Generated by Django 3.2.7 on 2021-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_good_from_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='from_url',
            field=models.URLField(),
        ),
    ]
