# Generated by Django 3.2.7 on 2021-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_good_from_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
