# Generated by Django 3.2.7 on 2021-12-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_good_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='detail',
        ),
    ]
