# Generated by Django 3.2.7 on 2021-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_good_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('com_url', models.URLField()),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to='shop/images/'),
        ),
    ]
