# Generated by Django 3.2.7 on 2021-12-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211207_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.good'),
        ),
    ]
