# Generated by Django 3.2.7 on 2021-12-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_company_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
