# Generated by Django 3.2.7 on 2021-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211207_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='size',
            field=models.ManyToManyField(to='shop.Size'),
        ),
    ]
