# Generated by Django 3.2.7 on 2021-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.ManyToManyField(to='shop.Color'),
        ),
    ]
