# Generated by Django 3.2.7 on 2021-12-18 04:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_good_user_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='about',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
