# Generated by Django 3.2.7 on 2021-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_good_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='shop/images/logo/'),
            preserve_default=False,
        ),
    ]
